### ISSUE TITLE
Maruku error: undefined method `captures' for nil:NilClass

### ISSUE THREAD

**Issue by adeel** [parasew/instiki#52]
We're running into what appears to be a Maruku bug on the nLab.  Certain pages are giving the following stacktrace when one tries to save them:

    undefined method `captures' for nil:NilClass

    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/ext/math/parsing.rb:98:in `block in <top (required)>'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/input/extensions.rb:23:in `call'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/input/extensions.rb:23:in `block in check_span_extensions'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/input/extensions.rb:21:in `each'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/input/extensions.rb:21:in `check_span_extensions'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/input/parse_span.rb:47:in `read_span'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/input/parse_span.rb:14:in `parse_span'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/input/parse_block.rb:289:in `read_paragraph'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/input/parse_block.rb:154:in `read_text_material'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/input/parse_block.rb:48:in `parse_blocks'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/ext/div.rb:83:in `block in <top (required)>'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/input/extensions.rb:53:in `call'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/input/extensions.rb:53:in `block in check_block_extensions'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/input/extensions.rb:50:in `each'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/input/extensions.rb:50:in `check_block_extensions'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/input/parse_block.rb:29:in `parse_blocks'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/input/parse_block.rb:20:in `parse_text_as_markdown'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/input/parse_doc.rb:35:in `parse_doc'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/maruku.rb:15:in `initialize'
    /home/nlab/www/nlab-prod/lib/chunks/engines.rb:76:in `new'
    /home/nlab/www/nlab-prod/lib/chunks/engines.rb:76:in `mask'
    /home/nlab/www/nlab-prod/lib/chunks/engines.rb:20:in `apply_to'
    /home/nlab/www/nlab-prod/lib/wiki_content.rb:182:in `build_chunks'
    /home/nlab/www/nlab-prod/lib/wiki_content.rb:158:in `initialize'
    /home/nlab/www/nlab-prod/lib/page_renderer.rb:140:in `new'
    /home/nlab/www/nlab-prod/lib/page_renderer.rb:140:in `render'
    /home/nlab/www/nlab-prod/lib/page_renderer.rb:29:in `display_content'
    /home/nlab/www/nlab-prod/app/models/page.rb:26:in `revise'
    /home/nlab/www/nlab-prod/app/models/wiki.rb:79:in `revise_page'
    /home/nlab/www/nlab-prod/app/controllers/wiki_controller.rb:375:in `save'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/base.rb:1333:in `perform_action'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:617:in `call_filters'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:638:in `block in run_before_filters'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:206:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:206:in `block in around_proc'
    /home/nlab/www/nlab-prod/vendor/rails/activesupport/lib/active_support/callbacks.rb:182:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/activesupport/lib/active_support/callbacks.rb:182:in `evaluate_method'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:184:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:635:in `run_before_filters'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:615:in `call_filters'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:638:in `block in run_before_filters'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:189:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:189:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:635:in `run_before_filters'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:615:in `call_filters'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:638:in `block in run_before_filters'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:189:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:189:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:635:in `run_before_filters'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:615:in `call_filters'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:610:in `perform_action_with_filters'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `block in perform_action_with_benchmark'
    /home/nlab/www/nlab-prod/vendor/rails/activesupport/lib/active_support/core_ext/benchmark.rb:17:in `block in ms'
    /home/nlab/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
    /home/nlab/www/nlab-prod/vendor/rails/activesupport/lib/active_support/core_ext/benchmark.rb:17:in `ms'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_with_benchmark'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/rescue.rb:160:in `perform_action_with_rescue'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/flash.rb:151:in `perform_action_with_flash'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/base.rb:532:in `process'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/filters.rb:606:in `process_with_filters'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/base.rb:391:in `process'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/base.rb:386:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/routing/route_set.rb:438:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:87:in `dispatch'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:121:in `_call'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:130:in `block in build_middleware_stack'
    /home/nlab/www/nlab-prod/vendor/rails/activerecord/lib/active_record/query_cache.rb:29:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/activerecord/lib/active_record/query_cache.rb:29:in `block in call'
    /home/nlab/www/nlab-prod/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
    /home/nlab/www/nlab-prod/vendor/rails/activerecord/lib/active_record/query_cache.rb:9:in `cache'
    /home/nlab/www/nlab-prod/vendor/rails/activerecord/lib/active_record/query_cache.rb:28:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/string_coercion.rb:25:in `call'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/gems/rack-1.4.5/lib/rack/head.rb:9:in `call'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/params_parser.rb:15:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/railties/lib/rails/rack/metal.rb:47:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/session/cookie_store.rb:99:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/failsafe.rb:26:in `call'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:106:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/railties/lib/rails/rack/static.rb:31:in `call'
    /home/nlab/www/nlab-prod/vendor/rails/railties/lib/rails/rack/log_tailer.rb:17:in `call'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:606:in `process_client'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:702:in `worker_loop'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:142:in `start'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/gems/unicorn-5.3.0/bin/unicorn_rails:209:in `<top (required)>'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bin/unicorn_rails:23:in `load'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bin/unicorn_rails:23:in `<main>'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bin/ruby_executable_hooks:15:in `eval'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bin/ruby_executable_hooks:15:in `<main>'`

The offending line of code seems to be

    eqid = src.read_regexp(RegEqref).captures.compact.first

in `lib/maruku/ext/math/parsing.rb`.

**Comment by adeel** [comment]
It looks like this happens when there is an equation reference (eq:xyz) which doesn't resolve.  It would be good if this can be handled gracefully.

**Comment by adeel** [comment]
A naive attempt to fix this didn't work:

    r = src.read_regexp(RegEqref)
    return false if r.nil?

as I then got a different error:

    undefined method `[]' for nil:NilClass

    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/ext/math/to_html.rb:158:in `to_html_eqref'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/output/to_html.rb:871:in `block in array_to_html'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/output/to_html.rb:864:in `each'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/output/to_html.rb:864:in `array_to_html'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/output/to_html.rb:859:in `children_to_html'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/output/to_html.rb:312:in `wrap_as_element'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/output/to_html.rb:393:in `to_html_paragraph'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/output/to_html.rb:871:in `block in array_to_html'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/output/to_html.rb:864:in `each'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/output/to_html.rb:864:in `array_to_html'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/output/to_html.rb:859:in `children_to_html'
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-c16d15a591da/lib/maruku/output/to_html.rb:23:in `to_html'

**Comment by distler** [comment]
Thanks for reporting.

Fixed in [this commit](https://github.com/distler/maruku/commit/8802684110f585682cb079cd52a657fc5d8fe07c).

**Comment by adeel** [comment]
Thanks!  Unfortunately after updating it is still failing with the same error:

    undefined method `captures&#39; for nil:NilClass

    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/ext/math/parsing.rb:102:in `block in &lt;top (required)&gt;&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/input/extensions.rb:23:in `call&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/input/extensions.rb:23:in `block in check_span_extensions&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/input/extensions.rb:21:in `each&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/input/extensions.rb:21:in `check_span_extensions&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/input/parse_span.rb:47:in `read_span&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/input/parse_span.rb:14:in `parse_span&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/input/parse_block.rb:289:in `read_paragraph&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/input/parse_block.rb:154:in `read_text_material&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/input/parse_block.rb:48:in `parse_blocks&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/ext/div.rb:83:in `block in &lt;top (required)&gt;&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/input/extensions.rb:53:in `call&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/input/extensions.rb:53:in `block in check_block_extensions&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/input/extensions.rb:50:in `each&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/input/extensions.rb:50:in `check_block_extensions&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/input/parse_block.rb:29:in `parse_blocks&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/input/parse_block.rb:20:in `parse_text_as_markdown&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/input/parse_doc.rb:35:in `parse_doc&#39;
    /home/nlab/.rvm/gems/ruby-2.2.1@nlab-prod/bundler/gems/maruku-8802684110f5/lib/maruku/maruku.rb:15:in `initialize&#39;

**Comment by distler** [comment]
Could you produce a minimal test case (a Maruku document which produces this error)?

**Comment by distler** [comment]
I guess you want to update to [this commit](https://github.com/distler/maruku/commit/7bb541043de27ba610f43cd7e39d0db25df8a7a0).

**Comment by adeel** [comment]
Thanks again.  With that latest commit I was still getting the same error, but I think I managed to fix the issue by [switching to CharSourceStrscan](https://github.com/adeel/maruku/commit/1bf1f70e95a233951da8a957bb90e7f1078a85f5).  Sorry I can't help debug CharSourceManual, it is surprisingly annoying to isolate what exactly was causing the problem.

**Comment by adeel** [comment]
I may have spoken too soon; switching to CharSourceStrscan resulted in errors of the form

    2017-10-11 05:40:09 -0400: #<ActionView::TemplateError: 
    ActionView::TemplateError (invalid byte sequence in UTF-8) on line #17 of app/views/wiki/page.rhtml:
    14:     <%= @renderer.display_diff %>
    15:   <%- else -%>
    16:     <%= @renderer.display_content %>
    17:   <%- end -%>
    18: </div>
    19: 

on a lot of pages.  I switched back to CharSourceManual for now.

**Comment by distler** [comment]
> Thanks again. With that latest commit I was still getting the same error, ...

If you can come up with a Maruku document which reliably produces the error, then we can track it down and fix it. Changing random stuff, and seeing whether than makes the error go away, is not going to get us there.

**Comment by adeel** [comment]
It was clear that the bug was in CharSourceManual, hence the decision to try CharSourceStrscan.  No randomness involved.

The reason for the byte sequence errors turned out to be pretty simple: [StringScanner](https://apidock.com/ruby/StringScanner) handles multibyte strings naively by default, so for example with the string "\xc3\xa9tale" (étale), cur_char would return "\xc3" instead of "étale".  I fixed that with [this commit](https://github.com/adeel/maruku/commit/a76a0ce9438103450d7aebc3670e546c792d64d1) and so far it seems to be working fine.

**Comment by distler** [comment]
> It was clear that the bug was in CharSourceManual, hence the decision to try CharSourceStrscan. No randomness involved.

"The bug". What *is* the bug you are talking about? Can you present a Maruku document that triggers it?

`CharSourceStrscan`, among its other problems, doesn't handle multibyte strings correctly. I'm glad to see that you've fixed that, but would want to do a lot more testing before considering a switch.

Also, please note that Ben Hollis's "official" distribution is not the same as my Nokogiri branch. The main point of departure is that he switched from Nokogiri back to REXML (much slower), in order to support jruby. While I have tried to backport many of the changes on my Nokogiri branch, there are certainly some that have not been backported.

**Comment by adeel** [comment]
I don't see the point of denying the existence of a bug when I posted the whole traceback and provided a link to the relevant nLab page.  Feel free to take a look at the source if you want.  I don't personally care whether you fix CharSourceManual and I don't care whether you switch to CharSourceStrscan, my only interest here is in keeping the nLab working.  Thanks.

**Comment by distler** [comment]
Whoah! Hold on. I'm not denying the existence of anything.

The only Nlab page you have pointed me to is the Sandbox, which changes *constantly*. I have no idea which version was responsible for the bug you were seeing. If I take the current version, it processes *just fine* in my installation of Instiki.

So I *still* have no idea what bug you were seeing, and it is impossible (obviously) to reverse-engineer what the bug *might* have been, from the stack-trace provided.
